pull the image

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -209,10 +209,7 @@ jobs:
 # Reference: https://github.com/OPM/ResInsight/blob/dev/.github/workflows/centos7.yml
   centos7-gcc:
     name:  centos7-${{ matrix.mode }}
-
     runs-on: ubuntu-20.04
-    container:
-      image: centos:7
     defaults:
       run:
         shell: bash
@@ -233,13 +230,6 @@ jobs:
       uses: styfle/cancel-workflow-action@0.11.0
       with:
         access_token: ${{ github.token }}
-        
-    - name: Install ssh-agent
-      run: |
-        yum install -y openssh-server openssh-clients
-        yum remove -y git*
-        yum install -y https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
-        yum install -y git
 
     - name: ssh-agent
       uses: webfactory/ssh-agent@v0.7.0
@@ -269,95 +259,75 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v3
         
-    - name: Install dependencies and build QT
+    - name: Checkout Subsystem
       run: |
-        bash .github/workflows/install_centos_dependencies_build.sh
-#        bash .github/workflows/install_litex_centos.sh 
+        set +e
+        make run-cmake-release ONLY_CHECKOUT_SUBSYSTEMS=ON
+        echo "Done"
 
     - name: Show shell configuration
-      run: |
-        env
-        source /opt/rh/devtoolset-11/enable
-        which gcc 
-        which g++ 
-
-    - name: Configure shell
-      run: |
-        source /opt/rh/devtoolset-11/enable
-        echo 'CC=/opt/rh/devtoolset-11/root/usr/bin/gcc' >> $GITHUB_ENV
-        echo 'CXX=/opt/rh/devtoolset-11/root/usr/bin/g++' >> $GITHUB_ENV
-        echo 'PATH=/usr/local/Qt-5.15.4/bin:/usr/lib/ccache:'"$PATH" >> $GITHUB_ENV
-        echo 'PREFIX=/tmp/raptor_gui-install' >> $GITHUB_ENV
-        echo "$PREFIX" >> $GITHUB_PATH
-        echo "ADDITIONAL_CMAKE_OPTIONS='-DMY_CXX_WARNING_FLAGS="-W -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Werror -UNDEBUG"'" >> $GITHUB_ENV
-        echo 'RULE_MESSAGES=off' >> $GITHUB_ENV
-        echo 'LC_ALL=en_US.utf-8' >> $GITHUB_ENV
-        echo 'LANG=en_US.utf-8' >> $GITHUB_ENV
-        if [ $event_type == 'workflow_dispatch' ]
-        then
-              echo 'p_devices="${{ inputs.Production_Devices }}"' >> $GITHUB_ENV
-        else
-              echo 'p_devices="$PRODUCTION_DEVICES"' >> $GITHUB_ENV
-        fi
-
-    - name: Configure git
-      run: |
-        git config --global --add safe.directory $GITHUB_WORKSPACE
-
-    - name: Test
-      if: matrix.mode == 'test'
-      run: |
-        make release test/batch
-
-    - name: Regression
-      id: reg_ok
-      if: matrix.mode == 'regression'
-      run: |
-        make release ADDITIONAL_CMAKE_OPTIONS=-DBUILD_YOSYS_PLUGINS=ON test/batch
-        make regression
-
-    - name: Production Build
-      # Change ref head to deploy using a different branch.
-      if: "${{ matrix.mode == 'production' && github.ref == 'refs/heads/main' }}"
-      run: |
-        echo -e "Production devices are\n\t${{ env.p_devices }}"
-        source /opt/rh/devtoolset-11/enable
-        mkdir /opt/instl_dir
-        make install PRODUCTION_BUILD=1 PREFIX=/opt/instl_dir PRODUCTION_DEVICES=${{ env.p_devices }} ${{ inputs.Release_Date }}
-        export LM_LICENSE_FILE=${GITHUB_WORKSPACE}/.github/bin/.raptor.lic
-        ./build/bin/raptor --batch --mute --script tests/tcl_examples/and2_verilog/run_raptor.tcl 
-        make clean && rm -rf yosys_verific_rs u-boot-rapidsi-dev zephyr-rapidsi-dev EmbeddedCommon-dev etc tests examples FOEDAG_rs IP_Catalog Backend
-        export LD_LIBRARY_PATH=/opt/instl_dir/lib64/raptor/lib:/usr/local/Qt-5.15.4/lib:$LD_LIBRARY_PATH
-        cd $GITHUB_WORKSPACE/Raptor_Tools/Create_Raptor_Artifact && bash create_release.sh  -C -w  /opt/instl_dir 
-
-    - name: Print server resource
-      if: success() || failure()
-      run: |
-        df -h  
-
-    - name: Check FTP server status
-      # Change ref head to deploy using a different branch.
-      if: "${{ matrix.mode == 'production' && github.ref == 'refs/heads/main' }}"
-      uses: appleboy/ssh-action@master
+      uses: addnab/docker-run-action@v3
       with:
-        host: ${{ secrets.FTP_IP }}
-        username: ${{ secrets.FTP_USER }}
-        key: ${{ secrets.FTP_KEY }}
-        port: ${{ secrets.FTP_PORT }}
-        script: whoami
+        username: ${{ github.actor }}
+        password: ${{ secrets.GITHUB_TOKEN }}
+        registry: gcr.io
+        image: ghcr.io/rapidsilicon/raptor:centos_with_docker
+        run: cmake --version  
 
-    - name: Deploy
-      # Change ref head to deploy using a different branch.
-      if: "${{ matrix.mode == 'production' && github.ref == 'refs/heads/main'}}"
-      #if: "${{ matrix.mode == 'regression'}}"
-      uses: appleboy/scp-action@master
-      with:
-         host: ${{ secrets.FTP_IP }}
-         username: ${{ secrets.FTP_USER }}
-         key: ${{ secrets.FTP_KEY }}
-         port: ${{ secrets.FTP_PORT }}
-         source: "./Raptor_Tools/upload/*"
-         target: "/home/rsbuilder/Raptor"
+#    - name: Test
+#      if: matrix.mode == 'test'
+#      run: |
+#        make release test/batch
+#
+#    - name: Regression
+#      id: reg_ok
+#      if: matrix.mode == 'regression'
+#      run: |
+#        make release ADDITIONAL_CMAKE_OPTIONS=-DBUILD_YOSYS_PLUGINS=ON test/batch
+#        make regression
+#
+#    - name: Production Build
+#      # Change ref head to deploy using a different branch.
+#      if: "${{ matrix.mode == 'production' && github.ref == 'refs/heads/main' }}"
+#      run: |
+#        echo -e "Production devices are\n\t${{ env.p_devices }}"
+#        source /opt/rh/devtoolset-11/enable
+#        mkdir /opt/instl_dir
+#        make install PRODUCTION_BUILD=1 PREFIX=/opt/instl_dir PRODUCTION_DEVICES=${{ env.p_devices }} ${{ inputs.Release_Date }}
+#        export LM_LICENSE_FILE=${GITHUB_WORKSPACE}/.github/bin/.raptor.lic
+#        ./build/bin/raptor --batch --mute --script tests/tcl_examples/and2_verilog/run_raptor.tcl 
+#        make clean && rm -rf yosys_verific_rs u-boot-rapidsi-dev zephyr-rapidsi-dev EmbeddedCommon-dev etc tests examples FOEDAG_rs IP_Catalog Backend
+#        export LD_LIBRARY_PATH=/opt/instl_dir/lib64/raptor/lib:/usr/local/Qt-5.15.4/lib:$LD_LIBRARY_PATH
+#        cd $GITHUB_WORKSPACE/Raptor_Tools/Create_Raptor_Artifact && bash create_release.sh  -C -w  /opt/instl_dir 
+#
+#    - name: Print server resource
+#      if: success() || failure()
+#      run: |
+#        df -h  
+#
+#    - name: Check FTP server status
+#      # Change ref head to deploy using a different branch.
+#      if: "${{ matrix.mode == 'production' && github.ref == 'refs/heads/main' }}"
+#      uses: appleboy/ssh-action@master
+#      with:
+#        host: ${{ secrets.FTP_IP }}
+#        username: ${{ secrets.FTP_USER }}
+#        key: ${{ secrets.FTP_KEY }}
+#        port: ${{ secrets.FTP_PORT }}
+#        script: whoami
+#
+#    - name: Deploy
+#      # Change ref head to deploy using a different branch.
+#      if: "${{ matrix.mode == 'production' && github.ref == 'refs/heads/main'}}"
+#      #if: "${{ matrix.mode == 'regression'}}"
+#      uses: appleboy/scp-action@master
+#      with:
+#         host: ${{ secrets.FTP_IP }}
+#         username: ${{ secrets.FTP_USER }}
+#         key: ${{ secrets.FTP_KEY }}
+#         port: ${{ secrets.FTP_PORT }}
+#         source: "./Raptor_Tools/upload/*"
+#         target: "/home/rsbuilder/Raptor"
        
 
 # Reference: https://github.com/eyllanesc/69108420/blob/main/.github/workflows/test.yml
